version: '2'
services:
  uifd:
    image: uifd/ui-for-docker
    privileged: true
    restart: always
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    build: .
    links:
     - uifd
    ports:
     - 9999:80
